from __future__ import annotations

import ctypes
import time
from ctypes import wintypes
from dataclasses import dataclass


user32 = ctypes.windll.user32
kernel32 = ctypes.windll.kernel32
dwmapi = ctypes.windll.dwmapi
imm32 = ctypes.windll.imm32

# Explicit signatures are required on 64-bit Windows so HWND/HANDLE values are
# not truncated to the default c_int return type.
user32.GetForegroundWindow.restype = wintypes.HWND
user32.GetWindowTextLengthW.argtypes = [wintypes.HWND]
user32.GetWindowTextLengthW.restype = ctypes.c_int
user32.GetWindowTextW.argtypes = [wintypes.HWND, wintypes.LPWSTR, ctypes.c_int]
user32.GetClassNameW.argtypes = [wintypes.HWND, wintypes.LPWSTR, ctypes.c_int]
user32.IsWindowVisible.argtypes = [wintypes.HWND]
user32.GetWindowThreadProcessId.argtypes = [wintypes.HWND, ctypes.POINTER(wintypes.DWORD)]
user32.GetWindowThreadProcessId.restype = wintypes.DWORD
user32.WindowFromPoint.argtypes = [wintypes.POINT]
user32.WindowFromPoint.restype = wintypes.HWND
user32.GetAncestor.argtypes = [wintypes.HWND, wintypes.UINT]
user32.GetAncestor.restype = wintypes.HWND
user32.IsWindow.argtypes = [wintypes.HWND]
user32.IsWindow.restype = wintypes.BOOL
user32.IsIconic.argtypes = [wintypes.HWND]
user32.IsIconic.restype = wintypes.BOOL
user32.SetForegroundWindow.argtypes = [wintypes.HWND]
user32.SetForegroundWindow.restype = wintypes.BOOL
user32.BringWindowToTop.argtypes = [wintypes.HWND]
user32.SetFocus.argtypes = [wintypes.HWND]
user32.SetFocus.restype = wintypes.HWND
user32.ShowWindow.argtypes = [wintypes.HWND, ctypes.c_int]
user32.ShowWindow.restype = wintypes.BOOL
user32.GetWindowLongW.argtypes = [wintypes.HWND, ctypes.c_int]
user32.GetWindowLongW.restype = ctypes.c_long
user32.SetWindowLongW.argtypes = [wintypes.HWND, ctypes.c_int, ctypes.c_long]
user32.SetWindowLongW.restype = ctypes.c_long
user32.SetWindowPos.argtypes = [
    wintypes.HWND, wintypes.HWND, ctypes.c_int, ctypes.c_int,
    ctypes.c_int, ctypes.c_int, wintypes.UINT,
]
user32.SetWindowPos.restype = wintypes.BOOL
user32.SendInput.argtypes = [wintypes.UINT, ctypes.c_void_p, ctypes.c_int]
user32.SendInput.restype = wintypes.UINT
user32.mouse_event.argtypes = [wintypes.DWORD, wintypes.DWORD, wintypes.DWORD, wintypes.DWORD, wintypes.WPARAM]
user32.keybd_event.argtypes = [wintypes.BYTE, wintypes.BYTE, wintypes.DWORD, wintypes.WPARAM]
user32.GetWindowRect.argtypes = [wintypes.HWND, ctypes.POINTER(wintypes.RECT)]
user32.GetWindowRect.restype = wintypes.BOOL
user32.GetClientRect.argtypes = [wintypes.HWND, ctypes.POINTER(wintypes.RECT)]
user32.GetClientRect.restype = wintypes.BOOL
user32.LoadKeyboardLayoutW.argtypes = [wintypes.LPCWSTR, wintypes.UINT]
user32.LoadKeyboardLayoutW.restype = wintypes.HANDLE
user32.ActivateKeyboardLayout.argtypes = [wintypes.HANDLE, wintypes.UINT]
user32.ActivateKeyboardLayout.restype = wintypes.HANDLE
user32.PostMessageW.argtypes = [wintypes.HWND, wintypes.UINT, wintypes.WPARAM, wintypes.LPARAM]
user32.PostMessageW.restype = wintypes.BOOL
user32.GetKeyboardLayout.argtypes = [wintypes.DWORD]
user32.GetKeyboardLayout.restype = wintypes.HANDLE
imm32.ImmGetContext.argtypes = [wintypes.HWND]
imm32.ImmGetContext.restype = wintypes.HANDLE
imm32.ImmSetOpenStatus.argtypes = [wintypes.HANDLE, wintypes.BOOL]
imm32.ImmSetOpenStatus.restype = wintypes.BOOL
imm32.ImmReleaseContext.argtypes = [wintypes.HWND, wintypes.HANDLE]
imm32.ImmReleaseContext.restype = wintypes.BOOL
kernel32.GetCurrentThreadId.restype = wintypes.DWORD
kernel32.GetCurrentProcessId.restype = wintypes.DWORD
kernel32.OpenProcess.argtypes = [wintypes.DWORD, wintypes.BOOL, wintypes.DWORD]
kernel32.OpenProcess.restype = wintypes.HANDLE
kernel32.QueryFullProcessImageNameW.argtypes = [wintypes.HANDLE, wintypes.DWORD, wintypes.LPWSTR, ctypes.POINTER(wintypes.DWORD)]
kernel32.QueryFullProcessImageNameW.restype = wintypes.BOOL
kernel32.CloseHandle.argtypes = [wintypes.HANDLE]
kernel32.CloseHandle.restype = wintypes.BOOL

INPUT_MOUSE = 0
INPUT_KEYBOARD = 1
# Identifies input packets generated by MacroFlow itself.  FocusInputGuard uses
# this marker so third-party mouse/keyboard drivers cannot bypass the lock just
# because Windows labels their packets as injected.
MACROFLOW_INPUT_TAG = 0x4D46574C
KEYEVENTF_KEYUP = 0x0002
KEYEVENTF_SCANCODE = 0x0008
KEYEVENTF_EXTENDEDKEY = 0x0001
KEYEVENTF_UNICODE = 0x0004
MOUSEEVENTF_MOVE = 0x0001
MOUSEEVENTF_LEFTDOWN = 0x0002
MOUSEEVENTF_LEFTUP = 0x0004
MOUSEEVENTF_RIGHTDOWN = 0x0008
MOUSEEVENTF_RIGHTUP = 0x0010
MOUSEEVENTF_MIDDLEDOWN = 0x0020
MOUSEEVENTF_MIDDLEUP = 0x0040
MOUSEEVENTF_WHEEL = 0x0800
MOUSEEVENTF_HWHEEL = 0x01000
MOUSEEVENTF_ABSOLUTE = 0x8000
MOUSEEVENTF_VIRTUALDESK = 0x4000

SW_RESTORE = 9
SW_SHOWNOACTIVATE = 4
SW_SHOW = 5
GA_ROOT = 2
PROCESS_QUERY_LIMITED_INFORMATION = 0x1000
GWL_EXSTYLE = -20
WS_EX_NOACTIVATE = 0x08000000
HWND_TOPMOST = -1
SWP_NOSIZE = 0x0001
SWP_NOMOVE = 0x0002
SWP_NOZORDER = 0x0004
SWP_NOACTIVATE = 0x0010
SWP_FRAMECHANGED = 0x0020
DWMWA_USE_IMMERSIVE_DARK_MODE = 20
DWMWA_CAPTION_COLOR = 35
DWMWA_TEXT_COLOR = 36
KLF_ACTIVATE = 0x00000001
WM_INPUTLANGCHANGEREQUEST = 0x0050
ENGLISH_US_LAYOUT = "00000409"
ENGLISH_US_LANGUAGE_ID = 0x0409


_input_dispatcher = None


def set_input_dispatcher(dispatcher) -> None:
    """Route SendInput packets through the system-input-lock owner thread."""
    global _input_dispatcher
    _input_dispatcher = dispatcher


ULONG_PTR = wintypes.WPARAM


def force_english_input(hwnd: int | None = None) -> bool:
    """Switch the target window to US English and close any active IME."""
    target = int(hwnd or user32.GetForegroundWindow() or 0)
    layout = user32.LoadKeyboardLayoutW(ENGLISH_US_LAYOUT, KLF_ACTIVATE)
    if not layout:
        return False
    layout_value = int(layout) if isinstance(layout, int) else int(layout.value)

    # Activate English for MacroFlow's thread and explicitly request the same
    # layout in the target/game thread, because Windows stores input languages
    # per GUI thread on many systems.
    user32.ActivateKeyboardLayout(layout, 0)
    if not target:
        return True

    handle = wintypes.HWND(target)
    for _ in range(2):
        user32.PostMessageW(handle, WM_INPUTLANGCHANGEREQUEST, 0, layout_value)
        context = imm32.ImmGetContext(handle)
        if context:
            try:
                imm32.ImmSetOpenStatus(context, False)
            finally:
                imm32.ImmReleaseContext(handle, context)
        time.sleep(0.025)

        thread_id = user32.GetWindowThreadProcessId(handle, None)
        active_layout = user32.GetKeyboardLayout(thread_id) if thread_id else 0
        if int(active_layout or 0) & 0xFFFF == ENGLISH_US_LANGUAGE_ID:
            return True
    # The request was still delivered even if the target does not expose its
    # active layout (some games hide or proxy the render window thread).
    return True


def _colorref(hex_color: str) -> int:
    value = hex_color.lstrip("#")
    red, green, blue = int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16)
    return red | (green << 8) | (blue << 16)


def set_dark_titlebar(hwnd: int, background: str = "#0E1419", foreground: str = "#E8EDF2") -> bool:
    """Apply a native dark caption to a Tk top-level window on Windows 10/11."""
    if not hwnd:
        return False
    root_hwnd = user32.GetAncestor(wintypes.HWND(hwnd), GA_ROOT) or wintypes.HWND(hwnd)
    enabled = ctypes.c_int(1)
    result = dwmapi.DwmSetWindowAttribute(
        root_hwnd, DWMWA_USE_IMMERSIVE_DARK_MODE,
        ctypes.byref(enabled), ctypes.sizeof(enabled),
    )
    caption = wintypes.DWORD(_colorref(background))
    text = wintypes.DWORD(_colorref(foreground))
    dwmapi.DwmSetWindowAttribute(root_hwnd, DWMWA_CAPTION_COLOR, ctypes.byref(caption), ctypes.sizeof(caption))
    dwmapi.DwmSetWindowAttribute(root_hwnd, DWMWA_TEXT_COLOR, ctypes.byref(text), ctypes.sizeof(text))
    return result == 0


class MOUSEINPUT(ctypes.Structure):
    _fields_ = [
        ("dx", wintypes.LONG), ("dy", wintypes.LONG),
        ("mouseData", wintypes.DWORD), ("dwFlags", wintypes.DWORD),
        ("time", wintypes.DWORD), ("dwExtraInfo", ULONG_PTR),
    ]


class KEYBDINPUT(ctypes.Structure):
    _fields_ = [
        ("wVk", wintypes.WORD), ("wScan", wintypes.WORD),
        ("dwFlags", wintypes.DWORD), ("time", wintypes.DWORD),
        ("dwExtraInfo", ULONG_PTR),
    ]


class HARDWAREINPUT(ctypes.Structure):
    _fields_ = [("uMsg", wintypes.DWORD), ("wParamL", wintypes.WORD), ("wParamH", wintypes.WORD)]


class INPUT_UNION(ctypes.Union):
    _fields_ = [("mi", MOUSEINPUT), ("ki", KEYBDINPUT), ("hi", HARDWAREINPUT)]


class INPUT(ctypes.Structure):
    _anonymous_ = ("u",)
    _fields_ = [("type", wintypes.DWORD), ("u", INPUT_UNION)]


@dataclass
class WindowInfo:
    hwnd: int
    title: str
    class_name: str
    process_path: str = ""
    window_rect: tuple[int, int, int, int] = (0, 0, 0, 0)
    client_size: tuple[int, int] = (0, 0)

    @property
    def label(self) -> str:
        return f"{self.title}  ·  {self.class_name}"


def get_process_image_path(process_id: int) -> str:
    if not process_id:
        return ""
    handle = kernel32.OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, False, int(process_id))
    if not handle:
        return ""
    try:
        size = wintypes.DWORD(32768)
        buffer = ctypes.create_unicode_buffer(size.value)
        if kernel32.QueryFullProcessImageNameW(handle, 0, buffer, ctypes.byref(size)):
            return buffer.value
    finally:
        kernel32.CloseHandle(handle)
    return ""


def get_window_info(hwnd: int | None) -> WindowInfo | None:
    if not hwnd or not is_window(hwnd):
        return None
    handle = wintypes.HWND(int(hwnd))
    length = user32.GetWindowTextLengthW(handle)
    title_buf = ctypes.create_unicode_buffer(max(1, length + 1))
    user32.GetWindowTextW(handle, title_buf, len(title_buf))
    class_buf = ctypes.create_unicode_buffer(256)
    user32.GetClassNameW(handle, class_buf, len(class_buf))
    process_id = wintypes.DWORD()
    user32.GetWindowThreadProcessId(handle, ctypes.byref(process_id))
    process_path = get_process_image_path(int(process_id.value))
    window_rect = wintypes.RECT()
    if user32.GetWindowRect(handle, ctypes.byref(window_rect)):
        rect = (int(window_rect.left), int(window_rect.top),
                int(window_rect.right - window_rect.left), int(window_rect.bottom - window_rect.top))
    else:
        rect = (0, 0, 0, 0)
    client_rect = wintypes.RECT()
    if user32.GetClientRect(handle, ctypes.byref(client_rect)):
        client_size = (int(client_rect.right - client_rect.left), int(client_rect.bottom - client_rect.top))
    else:
        client_size = (0, 0)
    return WindowInfo(int(hwnd), title_buf.value, class_buf.value, process_path, rect, client_size)


def window_from_point(x: int, y: int) -> WindowInfo | None:
    point = wintypes.POINT(int(x), int(y))
    hwnd = user32.WindowFromPoint(point)
    if hwnd:
        root = user32.GetAncestor(hwnd, GA_ROOT)
        if root:
            hwnd = root
    return get_window_info(int(hwnd)) if hwnd else None


def get_foreground_window_info() -> WindowInfo | None:
    hwnd = int(user32.GetForegroundWindow() or 0)
    return get_window_info(hwnd)


def enum_windows() -> list[WindowInfo]:
    result: list[WindowInfo] = []
    callback_type = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)

    @callback_type
    def callback(hwnd, _):
        if not user32.IsWindowVisible(hwnd):
            return True
        info = get_window_info(int(hwnd))
        if not info or not info.title:
            return True
        result.append(info)
        return True

    user32.EnumWindows(callback, 0)
    return sorted(result, key=lambda item: item.title.lower())


def is_window(hwnd: int | None) -> bool:
    return bool(hwnd and user32.IsWindow(wintypes.HWND(hwnd)))


def is_window_foreground(hwnd: int | None) -> bool:
    """Return whether the requested window currently owns keyboard focus."""
    if not hwnd or not is_window(hwnd):
        return False
    return int(user32.GetForegroundWindow()) == int(hwnd)


def is_window_process_foreground(hwnd: int | None) -> bool:
    """Accept focused child/render windows that belong to the target process."""
    if not hwnd or not is_window(hwnd):
        return False
    foreground = user32.GetForegroundWindow()
    if not foreground:
        return False
    if int(foreground) == int(hwnd):
        return True
    target_process_id = wintypes.DWORD()
    foreground_process_id = wintypes.DWORD()
    user32.GetWindowThreadProcessId(wintypes.HWND(hwnd), ctypes.byref(target_process_id))
    user32.GetWindowThreadProcessId(foreground, ctypes.byref(foreground_process_id))
    return bool(target_process_id.value and target_process_id.value == foreground_process_id.value)


def is_current_process_window(hwnd: int | None) -> bool:
    """Return whether a live window belongs to this running application."""
    if not hwnd or not is_window(hwnd):
        return False
    process_id = wintypes.DWORD()
    user32.GetWindowThreadProcessId(wintypes.HWND(hwnd), ctypes.byref(process_id))
    return bool(process_id.value == kernel32.GetCurrentProcessId())


def is_cursor_near_window_center(hwnd: int | None, tolerance: int = 8) -> bool:
    """Detect the stable center cursor used by first-person camera controls."""
    center_hwnd = int(hwnd) if hwnd else 0
    foreground = user32.GetForegroundWindow()
    if foreground and is_window_process_foreground(hwnd):
        # Launchers and render surfaces are often separate top-level windows in
        # the same game process. The focused render window owns the real center.
        center_hwnd = int(foreground)
    rect = get_window_rect(center_hwnd) if center_hwnd else None
    if not rect:
        return False
    x, y = get_cursor_pos()
    left, top, width, height = rect
    center_x = left + width // 2
    center_y = top + height // 2
    return abs(x - center_x) <= tolerance and abs(y - center_y) <= tolerance


def activate_window(hwnd: int) -> bool:
    if not is_window(hwnd):
        return False
    # SW_RESTORE also restores normal/maximized/full-screen windows to their
    # previous size. Only use it for an actually minimized window; foreground
    # activation must otherwise leave the user's window geometry untouched.
    if user32.IsIconic(wintypes.HWND(hwnd)):
        user32.ShowWindow(wintypes.HWND(hwnd), SW_RESTORE)
    current_thread = kernel32.GetCurrentThreadId()
    target_thread = user32.GetWindowThreadProcessId(wintypes.HWND(hwnd), None)
    attached = False
    if target_thread and target_thread != current_thread:
        attached = bool(user32.AttachThreadInput(current_thread, target_thread, True))
    try:
        user32.BringWindowToTop(wintypes.HWND(hwnd))
        user32.SetForegroundWindow(wintypes.HWND(hwnd))
        user32.SetFocus(wintypes.HWND(hwnd))
    finally:
        if attached:
            user32.AttachThreadInput(current_thread, target_thread, False)
    time.sleep(0.08)
    return int(user32.GetForegroundWindow()) == int(hwnd)


def show_window(hwnd: int) -> bool:
    """Make a window visible without changing a normal window's geometry."""
    if not is_window(hwnd):
        return False
    handle = wintypes.HWND(hwnd)
    command = SW_RESTORE if user32.IsIconic(handle) else SW_SHOW
    user32.ShowWindow(handle, command)
    return bool(user32.IsWindowVisible(handle))


def _send_input_direct(input_obj: INPUT) -> None:
    # SendInput can transiently return zero without setting LastError (which
    # previously surfaced as the contradictory "[WinError 0] 操作成功完成").
    # Retry first, then use the older event API for ordinary key/mouse packets.
    for attempt in range(3):
        ctypes.set_last_error(0)
        sent = user32.SendInput(1, ctypes.byref(input_obj), ctypes.sizeof(INPUT))
        if sent == 1:
            return
        if attempt < 2:
            time.sleep(0.01)
    if input_obj.type == INPUT_MOUSE:
        mouse = input_obj.mi
        user32.mouse_event(mouse.dwFlags, mouse.dx, mouse.dy, mouse.mouseData, mouse.dwExtraInfo)
        return
    if input_obj.type == INPUT_KEYBOARD and not (input_obj.ki.dwFlags & KEYEVENTF_UNICODE):
        key = input_obj.ki
        user32.keybd_event(key.wVk, key.wScan, key.dwFlags, key.dwExtraInfo)
        return
    raise RuntimeError("系统拒绝模拟输入，请确认目标程序与 MacroFlow 使用相同或更低的权限运行。")


def _send_input(input_obj: INPUT) -> None:
    dispatcher = _input_dispatcher
    if dispatcher is not None:
        dispatcher(input_obj)
        return
    _send_input_direct(input_obj)


def send_key(vk: int, down: bool, scan: int = 0, extended: bool = False) -> None:
    flags = 0 if down else KEYEVENTF_KEYUP
    if scan:
        flags |= KEYEVENTF_SCANCODE
    if extended:
        flags |= KEYEVENTF_EXTENDEDKEY
    inp = INPUT(type=INPUT_KEYBOARD)
    inp.ki = KEYBDINPUT(0 if scan else vk, scan, flags, 0, MACROFLOW_INPUT_TAG)
    _send_input(inp)


def send_text(text: str, char_delay_ms: int = 10) -> None:
    units = text.encode("utf-16-le", errors="surrogatepass")
    for index in range(0, len(units), 2):
        codepoint = units[index] | (units[index + 1] << 8)
        for flags in (KEYEVENTF_UNICODE, KEYEVENTF_UNICODE | KEYEVENTF_KEYUP):
            inp = INPUT(type=INPUT_KEYBOARD)
            inp.ki = KEYBDINPUT(0, codepoint, flags, 0, MACROFLOW_INPUT_TAG)
            _send_input(inp)
        if char_delay_ms:
            time.sleep(char_delay_ms / 1000)


def send_move_absolute(x: int, y: int) -> None:
    left = user32.GetSystemMetrics(76)
    top = user32.GetSystemMetrics(77)
    width = max(1, user32.GetSystemMetrics(78) - 1)
    height = max(1, user32.GetSystemMetrics(79) - 1)
    nx = round((x - left) * 65535 / width)
    ny = round((y - top) * 65535 / height)
    inp = INPUT(type=INPUT_MOUSE)
    inp.mi = MOUSEINPUT(
        nx, ny, 0,
        MOUSEEVENTF_MOVE | MOUSEEVENTF_ABSOLUTE | MOUSEEVENTF_VIRTUALDESK,
        0, MACROFLOW_INPUT_TAG,
    )
    _send_input(inp)


def send_move_relative(dx: int, dy: int) -> None:
    """Replay game deltas exactly as the working v1.2.1 implementation did."""
    inp = INPUT(type=INPUT_MOUSE)
    inp.mi = MOUSEINPUT(int(dx), int(dy), 0, MOUSEEVENTF_MOVE, 0, MACROFLOW_INPUT_TAG)
    _send_input(inp)


def _mouse_flags(button: str, down: bool) -> int:
    table = {
        ("left", True): MOUSEEVENTF_LEFTDOWN, ("left", False): MOUSEEVENTF_LEFTUP,
        ("right", True): MOUSEEVENTF_RIGHTDOWN, ("right", False): MOUSEEVENTF_RIGHTUP,
        ("middle", True): MOUSEEVENTF_MIDDLEDOWN, ("middle", False): MOUSEEVENTF_MIDDLEUP,
    }
    return table[(button, down)]


def send_button(button: str, down: bool) -> None:
    inp = INPUT(type=INPUT_MOUSE)
    inp.mi = MOUSEINPUT(0, 0, 0, _mouse_flags(button, down), 0, MACROFLOW_INPUT_TAG)
    _send_input(inp)


def send_scroll(dx: int, dy: int) -> None:
    if dy:
        inp = INPUT(type=INPUT_MOUSE)
        inp.mi = MOUSEINPUT(
            0, 0, ctypes.c_ulong(dy * 120).value, MOUSEEVENTF_WHEEL,
            0, MACROFLOW_INPUT_TAG,
        )
        _send_input(inp)
    if dx:
        inp = INPUT(type=INPUT_MOUSE)
        inp.mi = MOUSEINPUT(
            0, 0, ctypes.c_ulong(dx * 120).value, MOUSEEVENTF_HWHEEL,
            0, MACROFLOW_INPUT_TAG,
        )
        _send_input(inp)


def get_cursor_pos() -> tuple[int, int]:
    point = wintypes.POINT()
    user32.GetCursorPos(ctypes.byref(point))
    return point.x, point.y


def get_virtual_screen_rect() -> dict[str, int]:
    """Return the complete desktop coordinate space, including extra monitors."""
    return {
        "left": int(user32.GetSystemMetrics(76)),
        "top": int(user32.GetSystemMetrics(77)),
        "width": max(1, int(user32.GetSystemMetrics(78))),
        "height": max(1, int(user32.GetSystemMetrics(79))),
    }


def get_window_rect(hwnd: int) -> tuple[int, int, int, int] | None:
    rect = wintypes.RECT()
    if not is_window(hwnd) or not user32.GetWindowRect(hwnd, ctypes.byref(rect)):
        return None
    return rect.left, rect.top, rect.right - rect.left, rect.bottom - rect.top
def make_window_no_activate(hwnd: int) -> bool:
    """Keep a status overlay visible without taking focus from a game."""
    if not hwnd:
        return False
    handle = wintypes.HWND(hwnd)
    ex_style = user32.GetWindowLongW(handle, GWL_EXSTYLE)
    user32.SetWindowLongW(handle, GWL_EXSTYLE, ex_style | WS_EX_NOACTIVATE)
    return bool(user32.SetWindowPos(
        handle, wintypes.HWND(HWND_TOPMOST), 0, 0, 0, 0,
        SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE | SWP_FRAMECHANGED,
    ))


def show_window_no_activate(hwnd: int) -> bool:
    """Show a hidden window at its existing geometry without taking focus."""
    if not is_window(hwnd):
        return False
    handle = wintypes.HWND(hwnd)
    user32.ShowWindow(handle, SW_SHOWNOACTIVATE)
    return bool(user32.SetWindowPos(
        handle, wintypes.HWND(0), 0, 0, 0, 0,
        SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER | SWP_NOACTIVATE,
    ))
